# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EurekaSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EurekaSample

  target 'EurekaSampleTests' do

    pod 'Eureka'
    inherit! :search_paths
    # Pods for testing
  end

  target 'EurekaSampleUITests' do
    # Pods for testing
  end

end
